load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "files",
    srcs = [
        "directory.go",
        "file.go",
        "host.go",
        "option.go",
        "stats.go",
        "system.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/kernel/files",
    visibility = ["//visibility:public"],
)

go_test(
    name = "files_test",
    size = "small",
    srcs = [
        "directory_external_test.go",
        "file_external_test.go",
        "stats_external_test.go",
    ],
    deps = [
        ":files",
        "@com_github_stretchr_testify//assert",
    ],
)
