load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "buffer",
    srcs = [
        "buffer.go",
        "pool.go",
    ],
    importpath = "github.com/kitsunium/sdk/pkg/kernel/buffer",
    visibility = ["//visibility:public"],
)

go_test(
    name = "buffer_test",
    size = "small",
    srcs = [
        "buffer_test.go",
        "pool_test.go",
    ],
    deps = [
        ":buffer",
        "@com_github_stretchr_testify//assert",
    ],
)
