rules:
  - id: custom-unsafe-allowlist
    patterns:
      - pattern: unsafe.$FUNC(...)
      - pattern-not-inside: |
          // $PACKAGE kbuffer ...
          package kbuffer
          ...
    message: Using unsafe package outside of allowed kernel components
    languages: [go]
    severity: ERROR
    metadata:
      category: security
