load("@gazelle//:def.bzl", "gazelle")

# gazelle:prefix github.com/kistunium/sdk
# gazelle:exclude vendor
gazelle(name = "gazelle")

gazelle(
    name = "gazelle-update-repos",
    args = [
        "-from_file=go.mod",
        "-to_macro=deps.bzl%go_dependencies",
        "-prune",
    ],
    command = "update-repos",
)

# Alias for convenient commands
alias(
    name = "build",
    actual = "//pkg/...",
)

alias(
    name = "test",
    actual = "//pkg/...",
)