version: "3"
silent: true

tasks:
  default:
    cmds:
      - task -l
  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - npx prettier --write .
      - bazel run //:gazelle

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run ./...

  sec:
    desc: Run security checks
    cmds:
      - gosec -quiet -fmt text ./pkg/...

  check:
    desc: Run all checks (format, lint, security)
    cmds:
      - task: fmt
      - task: lint
      - task: sec

  update:
    desc: Update dependencies
    cmds:
      - go get -u ./...
      - go mod tidy
      - bazel mod tidy

  build:
    desc: Build all packages
    cmds:
      - bazel build //pkg/...

  test:
    desc: Run all tests
    cmds:
      - bazel test //pkg/... --test_output=errors
