version: '3'
silent: true

tasks:
  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - bazel run //:gazelle

  update:
    desc: Update dependencies
    cmds:
      - go get -u ./...
      - go mod tidy
      - bazel mod tidy

  build:
    desc: Build all packages
    cmds:
      - bazel build //pkg/...

  test:
    desc: Run all tests
    cmds:
      - bazel test //pkg/... --test_output=errors