load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "parser",
    srcs = [
        "args.go",
        "env.go",
        "errors.go",
        "ini.go",
        "interface.go",
        "json.go",
        "toml.go",
        "xml.go",
        "yaml.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/core/config/parser",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/core/config/normalize",
        "//internal/kernel/errs",
        "@com_github_pelletier_go_toml_v2//:go-toml",
        "@in_gopkg_yaml_v3//:yaml_v3",
    ],
)

go_test(
    name = "parser_test",
    srcs = [
        "args_internal_test.go",
        "env_internal_test.go",
        "ini_internal_test.go",
        "json_internal_test.go",
        "toml_internal_test.go",
        "xml_internal_test.go",
        "yaml_internal_test.go",
    ],
    data = glob(["testdata/**"]),
    embed = [":parser"],
)
