load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "errs",
    srcs = [
        "config.go",
        "context.go",
        "error.go",
        "instance.go",
        "metrics.go",
        "registry.go",
        "result.go",
    ],
    importpath = "github.com/kitsunium/sdk/pkg/kernel/errs",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/kernel/cache",
    ],
)

go_test(
    name = "errs_test",
    size = "small",
    timeout = "short",
    srcs = [
        "config_test.go",
        "context_test.go",
        "error_bench_test.go",
        "error_test.go",
        "instance_test.go",
        "metrics_test.go",
        "performance_test.go",
        "registry_test.go",
        "result_test.go",
    ],
    embed = [":errs"],
    deps = ["//pkg/kernel/cache"],
)

go_test(
    name = "bench",
    srcs = ["error_bench_test.go"],
    embed = [":errs"],
    tags = [
        "bench",
        "manual",
    ],
)
