load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "errs",
    srcs = [
        "context.go",
        "error.go",
        "instance.go",
    ],
    importpath = "github.com/kitsunium/sdk/internal/kernel/errs",
    visibility = ["//visibility:public"],
)

go_test(
    name = "errs_test",
    size = "small",
    timeout = "short",
    srcs = [
        "error_external_test.go",
        "error_internal_test.go",
        "export_test.go",
    ],
    embed = [":errs"],
)

go_test(
    name = "bench",
    srcs = ["error_bench_test.go"],
    embed = [":errs"],
    tags = [
        "bench",
        "manual",
    ],
)
