load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "metrics",
    srcs = [
        "counter.go",
        "gauge.go",
        "health.go",
        "metrics.go",
    ],
    importpath = "github.com/kitsunium/sdk/components/metrics",
    visibility = ["//visibility:public"],
)

go_test(
    name = "metrics_test",
    srcs = ["metrics_internal_test.go"],
    embed = [":metrics"],
)
