load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "normalize",
    srcs = [
        "key.go",
        "map.go",
        "value.go",
    ],
    importpath = "github.com/kistunium/sdk/pkg/kernel/config/normalize",
    visibility = ["//visibility:public"],
)

go_test(
    name = "normalize_test",
    size = "small",
    srcs = [
        "key_test.go",
        "map_test.go",
        "value_test.go",
    ],
    embed = [":normalize"],
    deps = [
        "@com_github_stretchr_testify//assert",
    ],
)