load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "value",
    srcs = ["value.go"],
    importpath = "github.com/kitsunium/sdk/pkg/lib/value",
    visibility = ["//visibility:public"],
)

go_test(
    name = "value_test",
    size = "small",
    srcs = ["value_test.go"],
    deps = [
        ":value",
        "@com_github_stretchr_testify//assert:assert",
    ],
)
