load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "parser",
    srcs = [
        "args.go",
        "env.go",
        "json.go",
        "xml.go",
        "yaml.go",
    ],
    importpath = "github.com/kitsunium/sdk/pkg/kernel/config/parser",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/kernel/config/normalize",
        "@in_gopkg_yaml_v3//:yaml_v3",
    ],
)

go_test(
    name = "parser_test",
    size = "small",
    srcs = [
        "args_test.go",
        "env_test.go",
        "json_test.go",
        "parser_test.go",
        "xml_test.go",
        "yaml_test.go",
    ],
    deps = [
        ":parser",
        "@com_github_stretchr_testify//assert",
        "@in_gopkg_yaml_v3//:yaml_v3",
    ],
)
