load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "logger",
    srcs = [
        "json.go",
        "logger.go",
        "text.go",
    ],
    importpath = "github.com/kitsunium/sdk/components/logger",
    visibility = ["//visibility:public"],
)

go_test(
    name = "logger_test",
    srcs = ["logger_internal_test.go"],
    embed = [":logger"],
)
