load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "fs",
    srcs = [
        "archive.go",
        "directory.go",
        "file.go",
        "host.go",
        "option.go",
        "stats.go",
        "system.go",
    ],
    importpath = "github.com/kitsunium/sdk/pkg/kernel/fs",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/lib/pointer",
        "@org_golang_x_sys//unix",
    ],
)

go_test(
    name = "fs_test",
    size = "small",
    srcs = [
        "archive_test.go",
        "directory_test.go",
        "file_test.go",
        "stats_test.go",
    ],
    deps = [
        ":fs",
        "//pkg/lib/pointer",
        "@com_github_stretchr_testify//assert",
    ],
)
